package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	httptransport "github.com/go-swagger/go-swagger/httpkit/client"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/client/v3"
)

// Default screwdriver API documentation HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new screwdriver API documentation HTTP client.
func NewHTTPClient(formats strfmt.Registry) *ScrewdriverAPIDocumentation {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("a4677c9873c9611e6aa7102b92f75d5c-1135862614.us-west-2.elb.amazonaws.com", "/", []string{"http"})
	return New(transport, formats)
}

// New creates a new screwdriver API documentation client
func New(transport client.Transport, formats strfmt.Registry) *ScrewdriverAPIDocumentation {
	cli := new(ScrewdriverAPIDocumentation)
	cli.Transport = transport

	cli.V3 = v3.New(transport, formats)

	return cli
}

// ScrewdriverAPIDocumentation is a client for screwdriver API documentation
type ScrewdriverAPIDocumentation struct {
	V3 *v3.Client

	Transport client.Transport
}

// SetTransport changes the transport on the client and all its subresources
func (c *ScrewdriverAPIDocumentation) SetTransport(transport client.Transport) {
	c.Transport = transport

	c.V3.SetTransport(transport)

}
