package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetV3PipelinesIDParams creates a new GetV3PipelinesIDParams object
// with the default values initialized.
func NewGetV3PipelinesIDParams() *GetV3PipelinesIDParams {
	var ()
	return &GetV3PipelinesIDParams{}
}

/*GetV3PipelinesIDParams contains all the parameters to send to the API endpoint
for the get v3 pipelines id operation typically these are written to a http.Request
*/
type GetV3PipelinesIDParams struct {

	/*ID
	  Identifier of this Pipeline

	*/
	ID string
}

// WithID adds the id to the get v3 pipelines id params
func (o *GetV3PipelinesIDParams) WithID(id string) *GetV3PipelinesIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetV3PipelinesIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
