package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetV3BuildsIDParams creates a new GetV3BuildsIDParams object
// with the default values initialized.
func NewGetV3BuildsIDParams() *GetV3BuildsIDParams {
	var ()
	return &GetV3BuildsIDParams{}
}

/*GetV3BuildsIDParams contains all the parameters to send to the API endpoint
for the get v3 builds id operation typically these are written to a http.Request
*/
type GetV3BuildsIDParams struct {

	/*ID
	  Identifier of this build

	*/
	ID string
}

// WithID adds the id to the get v3 builds id params
func (o *GetV3BuildsIDParams) WithID(id string) *GetV3BuildsIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetV3BuildsIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
