package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/models"
)

// GetV3PipelinesReader is a Reader for the GetV3Pipelines structure.
type GetV3PipelinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetV3PipelinesReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV3PipelinesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV3PipelinesOK creates a GetV3PipelinesOK with default headers values
func NewGetV3PipelinesOK() *GetV3PipelinesOK {
	return &GetV3PipelinesOK{}
}

/*GetV3PipelinesOK handles this case with default header values.

Successful
*/
type GetV3PipelinesOK struct {
	Payload models.ListOfPipelines
}

func (o *GetV3PipelinesOK) Error() string {
	return fmt.Sprintf("[GET /v3/pipelines][%d] getV3PipelinesOK  %+v", 200, o.Payload)
}

func (o *GetV3PipelinesOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
