package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetV3LoginReader is a Reader for the GetV3Login structure.
type GetV3LoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetV3LoginReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewGetV3LoginDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetV3LoginDefault creates a GetV3LoginDefault with default headers values
func NewGetV3LoginDefault(code int) *GetV3LoginDefault {
	return &GetV3LoginDefault{
		_statusCode: code,
	}
}

/*GetV3LoginDefault handles this case with default header values.

Successful
*/
type GetV3LoginDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the get v3 login default response
func (o *GetV3LoginDefault) Code() int {
	return o._statusCode
}

func (o *GetV3LoginDefault) Error() string {
	return fmt.Sprintf("[GET /v3/login][%d] getV3Login default  %+v", o._statusCode, o.Payload)
}

func (o *GetV3LoginDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
