package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetV3StatusParams creates a new GetV3StatusParams object
// with the default values initialized.
func NewGetV3StatusParams() *GetV3StatusParams {

	return &GetV3StatusParams{}
}

/*GetV3StatusParams contains all the parameters to send to the API endpoint
for the get v3 status operation typically these are written to a http.Request
*/
type GetV3StatusParams struct {
}

// WriteToRequest writes these params to a swagger request
func (o *GetV3StatusParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
