package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetV3BuildsIDLogsParams creates a new GetV3BuildsIDLogsParams object
// with the default values initialized.
func NewGetV3BuildsIDLogsParams() *GetV3BuildsIDLogsParams {
	var ()
	return &GetV3BuildsIDLogsParams{}
}

/*GetV3BuildsIDLogsParams contains all the parameters to send to the API endpoint
for the get v3 builds id logs operation typically these are written to a http.Request
*/
type GetV3BuildsIDLogsParams struct {

	/*ID
	  Identifier of this build

	*/
	ID string
}

// WithID adds the id to the get v3 builds id logs params
func (o *GetV3BuildsIDLogsParams) WithID(id string) *GetV3BuildsIDLogsParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetV3BuildsIDLogsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
