package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetV3JobsIDParams creates a new GetV3JobsIDParams object
// with the default values initialized.
func NewGetV3JobsIDParams() *GetV3JobsIDParams {
	var ()
	return &GetV3JobsIDParams{}
}

/*GetV3JobsIDParams contains all the parameters to send to the API endpoint
for the get v3 jobs id operation typically these are written to a http.Request
*/
type GetV3JobsIDParams struct {

	/*ID
	  Identifier of this Job

	*/
	ID string
}

// WithID adds the id to the get v3 jobs id params
func (o *GetV3JobsIDParams) WithID(id string) *GetV3JobsIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetV3JobsIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
