package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/models"
)

// GetV3PipelinesIDReader is a Reader for the GetV3PipelinesID structure.
type GetV3PipelinesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetV3PipelinesIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV3PipelinesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV3PipelinesIDOK creates a GetV3PipelinesIDOK with default headers values
func NewGetV3PipelinesIDOK() *GetV3PipelinesIDOK {
	return &GetV3PipelinesIDOK{}
}

/*GetV3PipelinesIDOK handles this case with default header values.

Successful
*/
type GetV3PipelinesIDOK struct {
	Payload *models.Model3
}

func (o *GetV3PipelinesIDOK) Error() string {
	return fmt.Sprintf("[GET /v3/pipelines/{id}][%d] getV3PipelinesIdOK  %+v", 200, o.Payload)
}

func (o *GetV3PipelinesIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Model3)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
