package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/models"
)

// GetV3JobsReader is a Reader for the GetV3Jobs structure.
type GetV3JobsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetV3JobsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV3JobsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV3JobsOK creates a GetV3JobsOK with default headers values
func NewGetV3JobsOK() *GetV3JobsOK {
	return &GetV3JobsOK{}
}

/*GetV3JobsOK handles this case with default header values.

Successful
*/
type GetV3JobsOK struct {
	Payload models.ListOfJobs
}

func (o *GetV3JobsOK) Error() string {
	return fmt.Sprintf("[GET /v3/jobs][%d] getV3JobsOK  %+v", 200, o.Payload)
}

func (o *GetV3JobsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
