package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/models"
)

// GetV3BuildsReader is a Reader for the GetV3Builds structure.
type GetV3BuildsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetV3BuildsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV3BuildsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV3BuildsOK creates a GetV3BuildsOK with default headers values
func NewGetV3BuildsOK() *GetV3BuildsOK {
	return &GetV3BuildsOK{}
}

/*GetV3BuildsOK handles this case with default header values.

Successful
*/
type GetV3BuildsOK struct {
	Payload models.ListOfBuilds
}

func (o *GetV3BuildsOK) Error() string {
	return fmt.Sprintf("[GET /v3/builds][%d] getV3BuildsOK  %+v", 200, o.Payload)
}

func (o *GetV3BuildsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
