package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetV3StatusReader is a Reader for the GetV3Status structure.
type GetV3StatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetV3StatusReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewGetV3StatusDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetV3StatusDefault creates a GetV3StatusDefault with default headers values
func NewGetV3StatusDefault(code int) *GetV3StatusDefault {
	return &GetV3StatusDefault{
		_statusCode: code,
	}
}

/*GetV3StatusDefault handles this case with default header values.

Successful
*/
type GetV3StatusDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the get v3 status default response
func (o *GetV3StatusDefault) Code() int {
	return o._statusCode
}

func (o *GetV3StatusDefault) Error() string {
	return fmt.Sprintf("[GET /v3/status][%d] getV3Status default  %+v", o._statusCode, o.Payload)
}

func (o *GetV3StatusDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
