package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// PostV3BuildsReader is a Reader for the PostV3Builds structure.
type PostV3BuildsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostV3BuildsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewPostV3BuildsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostV3BuildsDefault creates a PostV3BuildsDefault with default headers values
func NewPostV3BuildsDefault(code int) *PostV3BuildsDefault {
	return &PostV3BuildsDefault{
		_statusCode: code,
	}
}

/*PostV3BuildsDefault handles this case with default header values.

Successful
*/
type PostV3BuildsDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the post v3 builds default response
func (o *PostV3BuildsDefault) Code() int {
	return o._statusCode
}

func (o *PostV3BuildsDefault) Error() string {
	return fmt.Sprintf("[POST /v3/builds][%d] postV3Builds default  %+v", o._statusCode, o.Payload)
}

func (o *PostV3BuildsDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
