package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/models"
)

// PostV3ValidatorReader is a Reader for the PostV3Validator structure.
type PostV3ValidatorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostV3ValidatorReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostV3ValidatorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostV3ValidatorOK creates a PostV3ValidatorOK with default headers values
func NewPostV3ValidatorOK() *PostV3ValidatorOK {
	return &PostV3ValidatorOK{}
}

/*PostV3ValidatorOK handles this case with default header values.

Successful
*/
type PostV3ValidatorOK struct {
	Payload *models.Model4
}

func (o *PostV3ValidatorOK) Error() string {
	return fmt.Sprintf("[POST /v3/validator][%d] postV3ValidatorOK  %+v", 200, o.Payload)
}

func (o *PostV3ValidatorOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Model4)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
