package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/models"
)

// NewPostV3BuildsParams creates a new PostV3BuildsParams object
// with the default values initialized.
func NewPostV3BuildsParams() *PostV3BuildsParams {
	var ()
	return &PostV3BuildsParams{}
}

/*PostV3BuildsParams contains all the parameters to send to the API endpoint
for the post v3 builds operation typically these are written to a http.Request
*/
type PostV3BuildsParams struct {

	/*Body*/
	Body *models.CreateBuild
}

// WithBody adds the body to the post v3 builds params
func (o *PostV3BuildsParams) WithBody(body *models.CreateBuild) *PostV3BuildsParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostV3BuildsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.CreateBuild)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
