package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewPostV3LogoutParams creates a new PostV3LogoutParams object
// with the default values initialized.
func NewPostV3LogoutParams() *PostV3LogoutParams {

	return &PostV3LogoutParams{}
}

/*PostV3LogoutParams contains all the parameters to send to the API endpoint
for the post v3 logout operation typically these are written to a http.Request
*/
type PostV3LogoutParams struct {
}

// WriteToRequest writes these params to a swagger request
func (o *PostV3LogoutParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
