package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// PostV3PipelinesReader is a Reader for the PostV3Pipelines structure.
type PostV3PipelinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostV3PipelinesReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewPostV3PipelinesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostV3PipelinesDefault creates a PostV3PipelinesDefault with default headers values
func NewPostV3PipelinesDefault(code int) *PostV3PipelinesDefault {
	return &PostV3PipelinesDefault{
		_statusCode: code,
	}
}

/*PostV3PipelinesDefault handles this case with default header values.

Successful
*/
type PostV3PipelinesDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the post v3 pipelines default response
func (o *PostV3PipelinesDefault) Code() int {
	return o._statusCode
}

func (o *PostV3PipelinesDefault) Error() string {
	return fmt.Sprintf("[POST /v3/pipelines][%d] postV3Pipelines default  %+v", o._statusCode, o.Payload)
}

func (o *PostV3PipelinesDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
