package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/models"
)

// NewPostV3ValidatorParams creates a new PostV3ValidatorParams object
// with the default values initialized.
func NewPostV3ValidatorParams() *PostV3ValidatorParams {
	var ()
	return &PostV3ValidatorParams{}
}

/*PostV3ValidatorParams contains all the parameters to send to the API endpoint
for the post v3 validator operation typically these are written to a http.Request
*/
type PostV3ValidatorParams struct {

	/*Body*/
	Body *models.ValidationInput
}

// WithBody adds the body to the post v3 validator params
func (o *PostV3ValidatorParams) WithBody(body *models.ValidationInput) *PostV3ValidatorParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostV3ValidatorParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.ValidationInput)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
