package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// PostV3LogoutReader is a Reader for the PostV3Logout structure.
type PostV3LogoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostV3LogoutReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewPostV3LogoutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostV3LogoutDefault creates a PostV3LogoutDefault with default headers values
func NewPostV3LogoutDefault(code int) *PostV3LogoutDefault {
	return &PostV3LogoutDefault{
		_statusCode: code,
	}
}

/*PostV3LogoutDefault handles this case with default header values.

Successful
*/
type PostV3LogoutDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the post v3 logout default response
func (o *PostV3LogoutDefault) Code() int {
	return o._statusCode
}

func (o *PostV3LogoutDefault) Error() string {
	return fmt.Sprintf("[POST /v3/logout][%d] postV3Logout default  %+v", o._statusCode, o.Payload)
}

func (o *PostV3LogoutDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
