package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// PostV3WebhooksGithubReader is a Reader for the PostV3WebhooksGithub structure.
type PostV3WebhooksGithubReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostV3WebhooksGithubReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewPostV3WebhooksGithubDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostV3WebhooksGithubDefault creates a PostV3WebhooksGithubDefault with default headers values
func NewPostV3WebhooksGithubDefault(code int) *PostV3WebhooksGithubDefault {
	return &PostV3WebhooksGithubDefault{
		_statusCode: code,
	}
}

/*PostV3WebhooksGithubDefault handles this case with default header values.

Successful
*/
type PostV3WebhooksGithubDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the post v3 webhooks github default response
func (o *PostV3WebhooksGithubDefault) Code() int {
	return o._statusCode
}

func (o *PostV3WebhooksGithubDefault) Error() string {
	return fmt.Sprintf("[POST /v3/webhooks/github][%d] postV3WebhooksGithub default  %+v", o._statusCode, o.Payload)
}

func (o *PostV3WebhooksGithubDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
