package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewPostV3WebhooksGithubParams creates a new PostV3WebhooksGithubParams object
// with the default values initialized.
func NewPostV3WebhooksGithubParams() *PostV3WebhooksGithubParams {

	return &PostV3WebhooksGithubParams{}
}

/*PostV3WebhooksGithubParams contains all the parameters to send to the API endpoint
for the post v3 webhooks github operation typically these are written to a http.Request
*/
type PostV3WebhooksGithubParams struct {
}

// WriteToRequest writes these params to a swagger request
func (o *PostV3WebhooksGithubParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
