package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/models"
)

// NewPostV3WebhooksBuildParams creates a new PostV3WebhooksBuildParams object
// with the default values initialized.
func NewPostV3WebhooksBuildParams() *PostV3WebhooksBuildParams {
	var ()
	return &PostV3WebhooksBuildParams{}
}

/*PostV3WebhooksBuildParams contains all the parameters to send to the API endpoint
for the post v3 webhooks build operation typically these are written to a http.Request
*/
type PostV3WebhooksBuildParams struct {

	/*Body*/
	Body *models.BuildWebhook
}

// WithBody adds the body to the post v3 webhooks build params
func (o *PostV3WebhooksBuildParams) WithBody(body *models.BuildWebhook) *PostV3WebhooksBuildParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostV3WebhooksBuildParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.BuildWebhook)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
