package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/models"
)

// NewPostV3PipelinesParams creates a new PostV3PipelinesParams object
// with the default values initialized.
func NewPostV3PipelinesParams() *PostV3PipelinesParams {
	var ()
	return &PostV3PipelinesParams{}
}

/*PostV3PipelinesParams contains all the parameters to send to the API endpoint
for the post v3 pipelines operation typically these are written to a http.Request
*/
type PostV3PipelinesParams struct {

	/*Body*/
	Body *models.CreatePipeline
}

// WithBody adds the body to the post v3 pipelines params
func (o *PostV3PipelinesParams) WithBody(body *models.CreatePipeline) *PostV3PipelinesParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostV3PipelinesParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.CreatePipeline)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
