package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// PostV3WebhooksBuildReader is a Reader for the PostV3WebhooksBuild structure.
type PostV3WebhooksBuildReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostV3WebhooksBuildReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewPostV3WebhooksBuildDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostV3WebhooksBuildDefault creates a PostV3WebhooksBuildDefault with default headers values
func NewPostV3WebhooksBuildDefault(code int) *PostV3WebhooksBuildDefault {
	return &PostV3WebhooksBuildDefault{
		_statusCode: code,
	}
}

/*PostV3WebhooksBuildDefault handles this case with default header values.

Successful
*/
type PostV3WebhooksBuildDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the post v3 webhooks build default response
func (o *PostV3WebhooksBuildDefault) Code() int {
	return o._statusCode
}

func (o *PostV3WebhooksBuildDefault) Error() string {
	return fmt.Sprintf("[POST /v3/webhooks/build][%d] postV3WebhooksBuild default  %+v", o._statusCode, o.Payload)
}

func (o *PostV3WebhooksBuildDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
