package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/models"
)

// NewPutV3JobsIDParams creates a new PutV3JobsIDParams object
// with the default values initialized.
func NewPutV3JobsIDParams() *PutV3JobsIDParams {
	var ()
	return &PutV3JobsIDParams{}
}

/*PutV3JobsIDParams contains all the parameters to send to the API endpoint
for the put v3 jobs id operation typically these are written to a http.Request
*/
type PutV3JobsIDParams struct {

	/*Body*/
	Body *models.UpdateJob
	/*ID
	  Identifier of this Job

	*/
	ID string
}

// WithBody adds the body to the put v3 jobs id params
func (o *PutV3JobsIDParams) WithBody(body *models.UpdateJob) *PutV3JobsIDParams {
	o.Body = body
	return o
}

// WithID adds the id to the put v3 jobs id params
func (o *PutV3JobsIDParams) WithID(id string) *PutV3JobsIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutV3JobsIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.UpdateJob)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
