package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// PutV3PipelinesIDReader is a Reader for the PutV3PipelinesID structure.
type PutV3PipelinesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PutV3PipelinesIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewPutV3PipelinesIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPutV3PipelinesIDDefault creates a PutV3PipelinesIDDefault with default headers values
func NewPutV3PipelinesIDDefault(code int) *PutV3PipelinesIDDefault {
	return &PutV3PipelinesIDDefault{
		_statusCode: code,
	}
}

/*PutV3PipelinesIDDefault handles this case with default header values.

Successful
*/
type PutV3PipelinesIDDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the put v3 pipelines id default response
func (o *PutV3PipelinesIDDefault) Code() int {
	return o._statusCode
}

func (o *PutV3PipelinesIDDefault) Error() string {
	return fmt.Sprintf("[PUT /v3/pipelines/{id}][%d] putV3PipelinesId default  %+v", o._statusCode, o.Payload)
}

func (o *PutV3PipelinesIDDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
