package v3

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/screwdriver-cd/client/models"
)

// NewPutV3BuildsIDParams creates a new PutV3BuildsIDParams object
// with the default values initialized.
func NewPutV3BuildsIDParams() *PutV3BuildsIDParams {
	var ()
	return &PutV3BuildsIDParams{}
}

/*PutV3BuildsIDParams contains all the parameters to send to the API endpoint
for the put v3 builds id operation typically these are written to a http.Request
*/
type PutV3BuildsIDParams struct {

	/*Body*/
	Body *models.UpdateBuild
	/*ID
	  Identifier of this Job

	*/
	ID string
}

// WithBody adds the body to the put v3 builds id params
func (o *PutV3BuildsIDParams) WithBody(body *models.UpdateBuild) *PutV3BuildsIDParams {
	o.Body = body
	return o
}

// WithID adds the id to the put v3 builds id params
func (o *PutV3BuildsIDParams) WithID(id string) *PutV3BuildsIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutV3BuildsIDParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.UpdateBuild)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
