package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*CreatePipeline create pipeline

swagger:model Create Pipeline
*/
type CreatePipeline struct {

	/* Source Code URL for Screwdriver configuration
	 */
	ConfigURL *string `json:"configUrl,omitempty"`

	/* Source Code URL for the application

	Required: true
	*/
	ScmURL string `json:"scmUrl"`
}

// Validate validates this create pipeline
func (m *CreatePipeline) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateScmURL(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreatePipeline) validateScmURL(formats strfmt.Registry) error {

	if err := validate.RequiredString("scmUrl", "body", string(m.ScmURL)); err != nil {
		return err
	}

	return nil
}
