package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*CreateBuild create build

swagger:model Create Build
*/
type CreateBuild struct {

	/* Identifier of the Job

	Required: true
	*/
	JobID string `json:"jobId"`
}

// Validate validates this create build
func (m *CreateBuild) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJobID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateBuild) validateJobID(formats strfmt.Registry) error {

	if err := validate.RequiredString("jobId", "body", string(m.JobID)); err != nil {
		return err
	}

	return nil
}
