package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*GetPipeline get pipeline

swagger:model Get Pipeline
*/
type GetPipeline struct {

	/* Admins of this Pipeline

	Required: true
	*/
	Admins interface{} `json:"admins"`

	/* Source Code URL for Screwdriver configuration
	 */
	ConfigURL *string `json:"configUrl,omitempty"`

	/* When this pipeline was created

	Required: true
	*/
	// CreateTime strfmt.Date `json:"createTime"`
	CreateTime string `json:"createTime"`

	/* Identifier of this Pipeline

	Required: true
	*/
	ID string `json:"id"`

	/* Source Code URL for the application

	Required: true
	*/
	ScmURL string `json:"scmUrl"`
}

// Validate validates this get pipeline
func (m *GetPipeline) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdmins(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateCreateTime(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateScmURL(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetPipeline) validateAdmins(formats strfmt.Registry) error {

	return nil
}

func (m *GetPipeline) validateCreateTime(formats strfmt.Registry) error {

	if err := validate.Required("createTime", "body", m.CreateTime); err != nil {
		return err
	}

	return nil
}

func (m *GetPipeline) validateID(formats strfmt.Registry) error {

	if err := validate.RequiredString("id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *GetPipeline) validateScmURL(formats strfmt.Registry) error {

	if err := validate.RequiredString("scmUrl", "body", string(m.ScmURL)); err != nil {
		return err
	}

	return nil
}
