package models

import (
	"github.com/go-swagger/go-swagger/errors"
	// "github.com/go-openapi/strfmt"
	strfmt "github.com/go-swagger/go-swagger/strfmt"

)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Model2 model 2

swagger:model Model 2
*/
type Model2 struct {
	GetJob
}

// Validate validates this model 2
func (m *Model2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.GetJob.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
