package models

import (
	"github.com/go-openapi/errors"
	// "github.com/go-openapi/strfmt"
	strfmt "github.com/go-swagger/go-swagger/strfmt"

)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Model3 model 3

swagger:model Model 3
*/
type Model3 struct {
	GetPipeline
}

// Validate validates this model 3
func (m *Model3) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.GetPipeline.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
