package models

import (
	"github.com/go-openapi/errors"
	// "github.com/go-openapi/strfmt"
	strfmt "github.com/go-swagger/go-swagger/strfmt"

)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Model4 model 4

swagger:model Model 4
*/
type Model4 struct {
	ExecutionInformation
}

// Validate validates this model 4
func (m *Model4) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.ExecutionInformation.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
